[[ATK]]
arch = "x86_64"
git-tree-sha1 = "1367001f2905185637bff922e8a3ba875bc9f267"
os = "macos"

    [[ATK.download]]
    sha256 = "3a01b86e88506a5404e5ef6b7c19ff103cd7dd0365984c3467c224fb9cb7e4af"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.x86_64-apple-darwin14.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "7c98e755165d2849507cf21b96a535bd257b0f90"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "9ee321bcf8323cceb7645c5f590b1a4d7136a1d8ff896932c8f84257b9352d0c"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.i686-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "b5626254ce54a375a31439d555e45ea5ba700519"
os = "freebsd"

    [[ATK.download]]
    sha256 = "3a31bdf2f38f6c1e4ee2c31ce77d6f86fb3d55c916c5bec5a19b137d14ddc52e"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.x86_64-unknown-freebsd11.1.tar.gz"
[[ATK]]
arch = "powerpc64le"
git-tree-sha1 = "11d817323b74b92686575d68578208b3188f5f3a"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "6235fe776116c275c833a6cb6a9c0ad831ecc54759c5d699aa201f576042ddcf"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.powerpc64le-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "e473b5ab070d38b8cc1e25311ed7f2032fb33a71"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "3ecbb64be3036d7556fa25eca02858df2ed1e9f51e0b18f641640e1b571ac433"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.x86_64-linux-musl.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "e882ff6162c3bf30cc898deef77eae485c89580d"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "5a91e226c6e7600c754a6f085298578dcb660d279574f578a1bc8d1f6afdc9a0"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.x86_64-linux-gnu.tar.gz"
[[ATK]]
arch = "x86_64"
git-tree-sha1 = "9aba5ad74727983bce03686ca58202a0c67a31cd"
os = "windows"

    [[ATK.download]]
    sha256 = "2899f2bd9c9a6842a12e1f7feab4a74ecd996205b411afc008887b530d57e081"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.x86_64-w64-mingw32.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "360fbb882e8d529f33189a49833d38eab4be68fe"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "8c4b1ca9c6512eabba7d9d419cd2dfc982c9a6a7f96153c06053cf932a3a945c"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.aarch64-linux-musl.tar.gz"
[[ATK]]
arch = "armv7l"
git-tree-sha1 = "2cd731965b2ee6643d7451c2c42893fc4850a06c"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "352bc1e087eac8dd12f1b0aedd3f335a09846ef15f742a5a1ae430ca73120f47"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.arm-linux-gnueabihf.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "257464eb19025249655499d6fca642eaa0d95021"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "2aa13deb05cf96c2c1ae13195c6674e8241276f51a95befda96d4c5123ab9ab6"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.i686-linux-musl.tar.gz"
[[ATK]]
arch = "armv7l"
git-tree-sha1 = "de7f482209f2bd08fd71a9d3e8035cb81b795284"
libc = "musl"
os = "linux"

    [[ATK.download]]
    sha256 = "d55e7fdc86b59a64805024c2d0e54cb3e2f72f7d0969c3e833c2bc8864f8fdd3"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.arm-linux-musleabihf.tar.gz"
[[ATK]]
arch = "aarch64"
git-tree-sha1 = "49d9db773ff593fb5d1bb24bdf870b142dc90c8a"
libc = "glibc"
os = "linux"

    [[ATK.download]]
    sha256 = "1c455b552584a2bd9f33cdda4febc1522b68e805d7ab4122e9cfcd3e216c6b06"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.aarch64-linux-gnu.tar.gz"
[[ATK]]
arch = "i686"
git-tree-sha1 = "26004ea4fed321c999ee6e5c5e6d087da8c6c6f9"
os = "windows"

    [[ATK.download]]
    sha256 = "7b442bc6685631c6c098c1f891c8d6436302af9cd48fd32fd433d55ba0c3e9db"
    url = "https://github.com/JuliaBinaryWrappers/ATK_jll.jl/releases/download/ATK-v2.34.1+1/ATK.v2.34.1.i686-w64-mingw32.tar.gz"
